(load "type-tags.scm")

(define (real-part z)
  (cond ((rectangular? z) 
		 (real-part-rectangular (contents z)))
		((polar? z)
		 (real-part-polar (contents z)))
		(else (error "Unknown type -- REAL-PART" z))))
(define (imag-part z)
  (cond ((rectangular? z)
		 (imag-part-rectangular (contents z)))
		((polar? z)
		 (imag-part-polar (contents z)))
		(else (error "Unknown type -- IMAG-PART" z))))
(define (magnitude z)
  (cond ((rectangular? z)
		 (magnitude-rectangular (contents z)))
		((polar? z)
		 (magnitude-polar (contents z)))
		(else (error "Unknown type -- MAGNITUDE" z))))
(define (angle z)
  (cond ((rectangular? z)
		 (angle-rectangular (contents z)))
		((polar? z)
		 (angle-polar (contents z)))
		(else (error "Unknown type -- ANGLE" z))))

(define (make-from-real-imag x y)
  (make-from-real-imag-rectangular x y))
(define (make-from-mag-ang r a)
  (make-from-mag-ang-polar r a))

(define (make-from-real-imag-rectangular x y)
  (attach-tag 'rectangular (cons x y)))
(define (make-from-mag-ang-polar r a)
  (attach-tag 'polar (cons r a)))
